### ISSUE TITLE
Issue with API Custom Mode

### ISSUE THREAD

**Issue by TheEagle13** [devildant/OctoPrint-ShutdownPrinter#5]
I seem to be unable to get the Plugin to post to my webhook. I setup logging level to debugging for the plugin, but it doesn't create a log. and the following is the only reference I seem to be finding in the octoprint long to the plugin trying to work...

Your help would be appreciated

2018-07-18 15:02:18,715 - octoprint - ERROR - Exception on /api/plugin/shutdownprinter [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 1140, in decorated_view
    return flask_login.login_required(func)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 99, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_shutdownprinter/__init__.py", line 135, in on_api_command
    self._shutdown_printer_API_CMD( data["mode"]) #mode 1 = gcode, mode 2 = api, mode 3 = custom api
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_shutdownprinter/__init__.py", line 251, in _shutdown_printer_API_CMD
    self._shutdown_printer_by_API_custom()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_shutdownprinter/__init__.py", line 270, in _shutdown_printer_by_API_custom
    headers = json.loads(self.api_custom_json_header)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2018-07-18 15:02:18,718 - tornado.access - ERROR - 500 POST /api/plugin/shutdownprinter (::ffff:192.168.1) 185.31ms

**Comment by devildant** [comment]
Hello,

did you specify headers?
if yes could you show me this json ?

**Comment by TheEagle13** [comment]
headers are same as shown in your exmple:

Header:
{"Content-Type": "application/json"}

Body:
{"data": "PrintDone"}

**Comment by devildant** [comment]
can you make me a screenshot?
but this IP isn't normal "::ffff:192.168.1".

also check that yours is valid example : 
{**"**Content-Type**"**: **"**application/json**"**} = it's OK
{**'**Content-Type**'**: **'**application/json**'**} = KO

**Comment by devildant** [comment]
ok I have change the json lib by eval, could you reinstall the plugin and retry ? 
(https://github.com/devildant/OctoPrint-ShutdownPrinter/commit/f4676141dd138a2ce12142c413aeeb6f36e8cdbf)

**Comment by TheEagle13** [comment]
> but this IP isn't normal "::ffff:192.168.1".

I realize that now... I fat fingered that when I was replacing the PI's REAL IP.

Here's the requested Screenshot:
![image](https://user-images.githubusercontent.com/32144818/42974193-dacfa4ba-8b7b-11e8-9d2c-4a3212a4b66f.png)

I tried re-installing, but it appears something is broken:

Installing plugin "ShutdownPrinter" from https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/master.zip...
/home/pi/oprint/bin/python -m pip install https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/master.zip --no-cache-dir
Collecting https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/master.zip
Exception:
Traceback (most recent call last):
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
requirement_set.prepare_files(finder)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
session=self.session, hashes=hashes)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
hashes=hashes
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
hashes)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
stream=True,
File "/home/pi/oprint/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
return self.request('GET', url, **kwargs)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
return super(PipSession, self).request(method, url, *args, **kwargs)
File "/home/pi/oprint/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/home/pi/oprint/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/home/pi/oprint/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
timeout=timeout
File "/home/pi/oprint/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
_stacktrace=sys.exc_info()[2])
File "/home/pi/oprint/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by devildant** [comment]
mm it's octoprint, uninstall the plugin, and install again with this link https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/master.zip

**Comment by TheEagle13** [comment]
Ok, it is re-installed. But it seems like it's doing nothing. 
Even though I have set the plugin to Debug in logging, it doesn't log anything, and the only entry in the octoprint log is:

`2018-07-19 23:58:06,690 - octoprint.plugins.shutdownprinter - INFO - Shutting down printer with API custom (POST)`

I am even trying testing it against https://webhook.site to make sure it's not just my server, and there is no record of it even attempting to do anything.

**Comment by devildant** [comment]
hoo, i forgot to push my previous fixes.
sorry could you try uninstall.install again ?

**Comment by TheEagle13** [comment]
There we go! She works now. Thanks for your help!
